config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #verb  'path', to: "controller#action"
  root to: 'pages#home'

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  # get '/lewagon', to: 'lewagon#test'

end



# routes -> controller -> view

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
    search = params[:member]
    @team = ['Ben', 'Rebecca', 'Maria', 'Milene', 'Felipe']

    if search.present?
      @team = @team.select { |name| name.downcase == search.downcase }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style='background: lightgreen; padding: 16px'>
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Contact', contact_path %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is our about page</h1>

app/views/pages/contact.html.erb
<h1>This is our contact page</h1>

<ul>
  <% @team.each do |name| %>
    <li> <%= name %>  </li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Welcome to our website</h1>


<p>Today is <%= Date.today %>  </p>

<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?">
  <input type="submit">
</form>


<!-- er + tab = ruby code / does not appear to the user -->
<%  %>

<!-- pe + tab = ruby code / does appear to the user -->
<%=  %>